---
- name: Ensure required packagesfor this role are installed (Debian)
  ansible.builtin.apt:
    name:
      - python3-debian      # for ansible.builtin.deb822_repository module
    state: present
    update_cache: true
  when: ansible_facts['os_family'] == "Debian"
  tags: es-preflight

- name: Configure elasticsearch 8.x repository (RedHat)
  ansible.builtin.yum_repository:
    name: elasticsearch
    description: Elasticsearch repository for 8.x packages
    file: elasticsearch
    gpgkey: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    gpgcheck: true
    baseurl: https://artifacts.elastic.co/packages/8.x/yum
    enabled: false      # repo is disabled by default
  when: ansible_facts['os_family'] == "RedHat"
  tags: es-repo

- name: Configure elasticsearch 8.x repository (Debian)
  ansible.builtin.deb822_repository:
    name: elasticsearch
    types: [deb]
    uris: ["https://artifacts.elastic.co/packages/8.x/apt"]
    suites: [stable]
    components: [main]
    signed_by: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
  when: ansible_facts['os_family'] == "Debian"
  tags: es-repo

- name: Install elasticsearch package from repository (RedHat)
  ansible.builtin.dnf:
    name: elasticsearch-{{ es_version }}
    enablerepo: elasticsearch
    update_cache: true
  when: ansible_facts['os_family'] == "RedHat"
  notify:
    - Restart systemd elasticsearch service (with daemon-reload)
  tags: es-pkg

- name: Install elasticsearch package from repository (Debian)
  ansible.builtin.apt:
    name: "elasticsearch={{ es_version }}"
    update_cache: true
  when: ansible_facts['os_family'] == "Debian"
  notify:
    - Restart systemd elasticsearch service (with daemon-reload)
  tags: es-pkg

- name: Configure JVM heap size if defined
  ansible.builtin.template:
    src: etc/elasticsearch/jvm.options.d/heapsize.options.j2
    dest: /etc/elasticsearch/jvm.options.d/heapsize.options
    owner: root
    group: elasticsearch
    mode: '0660'
    backup: true
  when: es_heap_size is defined
  tags: es-cfg
  notify:
    - Restart systemd elasticsearch service (with daemon-reload)

- name: Update ES config files (RedHat)
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: root
    group: elasticsearch
    mode: '0660'
    backup: true
  loop:
    - etc/elasticsearch/elasticsearch.yml
    - etc/sysconfig/elasticsearch
  when: ansible_facts['os_family'] == "RedHat"
  tags: es-cfg
  notify:
    - Restart systemd elasticsearch service (with daemon-reload)

- name: Update ES config files (Debian)
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: root
    group: elasticsearch
    mode: '0660'
    backup: true
  loop:
    - etc/elasticsearch/elasticsearch.yml
    - etc/default/elasticsearch
  when: ansible_facts['os_family'] == "Debian"
  tags: es-cfg
  notify:
    - Restart systemd elasticsearch service (with daemon-reload)

# Need a systemd config override to allow memory locking by ES
- name: Block to configure systemd config override
  tags: es-cfg
  block:
    - name: Create systemd override directory
      ansible.builtin.file:
        path: /etc/systemd/system/elasticsearch.service.d
        state: directory
        owner: root
        group: root
        mode: u=rwx,g=rx,o=rx

    - name: Configure elasticsearch systemd override (LimitMEMLock)
      ansible.builtin.template:
        src: etc/systemd/system/elasticsearch.service.d/override.conf.j2
        dest: /etc/systemd/system/elasticsearch.service.d/override.conf
        owner: root
        group: root
        mode: "0644"
      notify:
        - Restart systemd elasticsearch service (with daemon-reload)

# Temporary directory
# https://www.elastic.co/guide/en/elasticsearch/reference/8.19/executable-jna-tmpdir.html
# https://www.elastic.co/docs/deploy-manage/deploy/self-managed/important-settings-configuration#es-tmpdir
- name: Create ES temporary directory
  ansible.builtin.file:
    path: "{{ es_tmpdir }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: u=rwx,g=rx
  when:
    - es_tmpdir is defined
    - es_tmpdir_create is defined and es_tmpdir_create
  notify:
    - Restart systemd elasticsearch service (with daemon-reload)
  tags: es-tmpdir
